### PR TITLE
IO<E, A>: remove `E` from cancel tokens

### LINKED ISSUE #149: FlatMap between BIOs
```
class OneError
class TwoError

private fun oneEither(): Either<OneError, String> = OneError().left()
private fun twoEither(value: String): Either<TwoError, Int> = value.toInt().right()

fun either() {
   oneEither()
     .flatMap { twoEither(it) }
     .fold(
       { throw Exception(it::class.simpleName) },
       { ... }
     )
}

private fun oneIO(): IO<OneError, String> = IO.raiseError(OneError())
private fun twoIO(value: String): IO<TwoError, Int> = IO.just(value.toInt())

fun io() {
   oneIO()
     .flatMap { twoIO(it) }
     .unsafeRunSyncEither()
     .fold(
       { throw Exception(it::class.simpleName) },
       { ... }
     )
}
```

The function `either` throws `java.lang.Exception: OneError` as I expect. But the function `io` throws `OneError cannot be cast to class TwoError`. When I look at the signature of `flatMap` (`fun <E, A, B, E2 : E> IOOf<E, A>.flatMap(f: (A) -> IOOf<E2, B>): IO<E2, B>`), it seems that it shouldn't even compile (`E2 : E`).

Should BIO behave like Either?

I've been informed to tag @nomisRev and @raulraja.

### PR DESCRIPTION
**Pull request by nomisRev**
This removes `E` from all cancel tokens. This was left over from an attempt to write partially applied `Bracket` up to `Concurrent` for `IO<E, A>` but it only supports `IO<Nothing, A>`.

This also fixes #149.

### CODE REVIEW

**Comment by nomisRev** [comment]
@rachelcarmena seems I broke Ank with a breaking change in Fx is that possible?

**Comment by pakoito** [comment]
`handleErrorWith` seems to require an uncessary subtyping relationship too. @Hiosdra raised it here: https://kotlinlang.slack.com/archives/C5UPMM0A0/p1589063333198800?thread_ts=1589063327.198600&cid=C5UPMM0A0

**Comment by rachelcarmena** [comment]
> @rachelcarmena seems I broke Ank with a breaking change in Fx is that possible?

Sorry mate, I missed this question. I'll check it right now.

**Comment by rachelcarmena** [comment]
Oh, I cannot check it because of compilation errors:

```
> Task :arrow-fx:compileKotlin
e: /home/runner/work/arrow-fx/arrow-fx/arrow-fx/src/main/kotlin/arrow/fx/IO.kt: (23, 37): Unresolved reference: effectMap
e: /home/runner/work/arrow-fx/arrow-fx/arrow-fx/src/main/kotlin/arrow/fx/IO.kt: (1093, 3): Type inference failed: fun <B> effectMap(f: (A) -> B#1 (type parameter of arrow.fx.IO.effectMap)): IO<E, B#1>
cannot be applied to
(suspend (A) -> EitherOf<E, B#2 (type parameter of arrow.fx.effectMapEither)> /* = Kind<Kind<ForEither, E>, B#2> */)

e: /home/runner/work/arrow-fx/arrow-fx/arrow-fx/src/main/kotlin/arrow/fx/IO.kt: (1093, 13): Type mismatch: inferred type is suspend (A) -> EitherOf<E, B> /* = Kind<Kind<ForEither, E>, B> */ but (A) -> ??? was expected
```

**Comment by nomisRev** [comment]
I'm closing this PR since we'll be reverting back to our original `IO` implementation from `0.10.5` given the new `Arrow Fx Coroutines` library 🎉

**Pull request closed without merging**
