### PR TITLE
Deprecate parTupledN

### PR DESCRIPTION
**Pull request by LordRaydenMK**
## Issue
Fixes https://github.com/arrow-kt/arrow-fx/issues/374

## Status
**READY**

## Description
Removes parTupledN arity 4 and 5
Deprecates parTupledN arity 2 and 3

### CODE REVIEW

**Comment by LordRaydenMK** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':arrow-docs'.
> Could not resolve all artifacts for configuration ':arrow-docs:classpath'.
   > Could not find io.arrow-kt:arrow-ank-gradle:0.12.0-SNAPSHOT.
     Searched in the following locations:
       - file:/Users/runner/.m2/repository/io/arrow-kt/arrow-ank-gradle/0.12.0-SNAPSHOT/maven-metadata.xml
       - file:/Users/runner/.m2/repository/io/arrow-kt/arrow-ank-gradle/0.12.0-SNAPSHOT/arrow-ank-gradle-0.12.0-SNAPSHOT.pom
       - https://plugins.gradle.org/m2/io/arrow-kt/arrow-ank-gradle/0.12.0-SNAPSHOT/maven-metadata.xml
       - https://plugins.gradle.org/m2/io/arrow-kt/arrow-ank-gradle/0.12.0-SNAPSHOT/arrow-ank-gradle-0.12.0-SNAPSHOT.pom
     Required by:
         project :arrow-docs
```

Not sure what's happening here

**Comment by rachelcarmena** [comment]
> Not sure what's happening here

Hi @LordRaydenMK , thanks for your contributions :raised_hands: 

The initial error is:

```
2021-01-15T19:20:28.6249720Z --------------------------------------------------------------------------------
2021-01-15T19:20:28.6251840Z arrow-core > Local install
2021-01-15T19:20:28.6253150Z --------------------------------------------------------------------------------
2021-01-15T19:20:28.6253880Z 
2021-01-15T19:20:28.6254810Z Exception in thread "main" javax.net.ssl.SSLException: readHandshakeRecord
2021-01-15T19:20:28.6256430Z 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
2021-01-15T19:20:28.6258150Z 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:394)
2021-01-15T19:20:28.6259980Z 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
...
2021-01-15T19:20:28.6300260Z Caused by: java.net.SocketException: Broken pipe (Write failed)
2021-01-15T19:20:28.6301400Z 	at java.net.SocketOutputStream.socketWrite0(Native Method)
2021-01-15T19:20:28.6302640Z 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
2021-01-15T19:20:28.6303900Z 	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
...
```

and that error impacts on the rest of tasks.

Just re-run when it appears. It's re-running now!!

**Review by i-walker — APPROVED** [review]
Thanks @LordRaydenMK 😄

**Comment by LordRaydenMK** [comment]
Thanks @rachelcarmena for pointing out the issues and re-triggering the build. I don't think I have the permission for triggering builds :smile:

**Review by nomisRev — APPROVED** [review]
Perfect @LordRaydenMK! 😍  Thanks for the quick follow up and contribution! 🎉

**Comment by rachelcarmena** [comment]
> Thanks @rachelcarmena for pointing out the issues and re-triggering the build. I don't think I have the permission for triggering builds smile

Oh, sorry, thanks for letting me know. You can push an empty commit to trigger them as well :raised_hands:

**Pull request merged**
