### PR TITLE
Address `Either.catch` inline incompatibility.

### PR DESCRIPTION
**Pull request by joramnv**
This PR relates to the change to inline the `Either.catch` which is in this PR: https://github.com/arrow-kt/arrow-core/pull/237.

Somehow, the compiler is not happy with the current usage at line 238 in combination with the inlined version of `Either.catch`. This PR addresses that issue by incorporating the `Either.catch` functionality in the internal `go` function.

### CODE REVIEW

**Comment by rachelcarmena** [comment]
Hi @joramnv :wave: Thank you so much! Please, close this pull request and open a new one with the same branch name as https://github.com/arrow-kt/arrow-core/pull/237 In that case, integration checks will use both pull requests at the same time. Thanks!!

**Comment by rachelcarmena** [comment]
> Hi @joramnv wave Thank you so much! Please, close this pull request and open a new one with the same branch name as [arrow-kt/arrow-core#237](https://github.com/arrow-kt/arrow-core/pull/237) In that case, integration checks will use both pull requests at the same time. Thanks!!

`(*)` all the checks, not only integration ones

More info: https://github.com/arrow-kt/arrow/blob/master/docs/libraries/how-to-propose-an-improvement.md#what-happens-when-creating-a-pull-request

**Comment by joramnv** [comment]
> Hi @joramnv 👋 Thank you so much! Please, close this pull request and open a new one with the same branch name as [arrow-kt/arrow-core#237](https://github.com/arrow-kt/arrow-core/pull/237) In that case, integration checks will use both pull requests at the same time. Thanks!!

Done. See: https://github.com/arrow-kt/arrow-fx/pull/288.
Cool feature. 😃

**Comment by nomisRev** [comment]
Thanks @joramnv!

**Pull request closed without merging**
