### PR TITLE
Fix Schedule type in retry methods

### PR DESCRIPTION
**Pull request by 1Jajen1**

### CODE REVIEW

**Review by nomisRev — APPROVED** [review]
If you're up for it, it'd be great to add some tests for `retry`.

**Comment by 1Jajen1** [comment]
> If you're up for it, it'd be great to add some tests for `retry`.

Yeah I'll do that. Should be pretty quick to add :+1:

**Comment by nomisRev** [comment]
Requested maintainers review for the second review 👍

**Review by aballano — APPROVED** [review]
Thank you @1Jajen1!!

**Comment by 1Jajen1** [comment]
Thanks @aballano :+1:

**Pull request merged**
